name: "Package CI"

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'  # Caching pip dependencies
          
      # Install system dependencies for RE2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          # Install abseil (required for RE2)
          sudo apt-get install -y libabsl-dev || sudo apt-get install -y libabsl-cpp-dev || echo "Abseil not available in apt, will build from source during pip install"
          
      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[docs, dev, re2]"
          
      - name: Run Tests
        run: |
          make test-ci
          
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: build docs
        run: |
          make docs-ci
          
      - name: save docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_site

      # deploy ----
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true