name: "Publish"

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
    publish-testpypi:
        name: Publish to TestPyPI
        runs-on: ubuntu-latest
        # Only publish on release
        if: github.event_name == 'release' && github.event.action == 'published'
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - uses: actions/setup-python@v5
            with:
              python-version: "3.10"
          - name: Install build dependencies
            run: python -m pip install build twine
          - name: Build package
            run: python -m build
          - name: Publish to Test PyPI
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
              password: ${{ secrets.TEST_PYPI_API_TOKEN }}
              repository-url: https://test.pypi.org/legacy/